        SUBROUTINE GETELEMNUMBER(LOCNUM, JTYPE, USER_NUMBER, JRCD)
        INCLUDE 'ABA_PARAM.INC'
        CHARACTER INSTANCE*80
        CALL GETPARTINFO(LOCNUM, JTYPE, INSTANCE, ELEM_NUMBER, JRCD)
        END