        SUBROUTINE GETELEMNUMBER(LOCNUM, JTYPE, USER_NUMBER, JRCD)
        EXTERNAL GETPARTINFO
        CHARACTER INSTANCE*80
        CALL GETPARTINFO(LOCNUM, JTYPE, INSTANCE, ELEM_NUMBER, JRCD)
        END